### ISSUE TITLE
Erro ao realizar ativação da maquineta

### ISSUE THREAD

**Issue by unleed-l** [Leleocastro/stone_payments#12]
Ao tentar realizar a ativação da maquineta, ocorre o erro abaixo e o app crasha.
Obs¹: utilizei o example do package.
Obs²: Testado na L400.

```
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Connecting to VM Service at ws://127.0.0.1:56957/cbLy8ES86jI=/ws
Connected to the VM Service.
V/StoneStart( 3921): init()
W/ayments_exampl( 3921): Accessing hidden method Landroid/os/ServiceManager;->getService(Ljava/lang/String;)Landroid/os/IBinder; (greylist, linking, allowed)
W/ayments_exampl( 3921): Accessing hidden method Landroid/util/Log;->println_native(IILjava/lang/String;Ljava/lang/String;)I (greylist, linking, allowed)
E/AndroidRuntime( 3921): FATAL EXCEPTION: Thread-7
E/AndroidRuntime( 3921): Process: dev.ltag.stone_payments_example, PID: 3921
E/AndroidRuntime( 3921): java.lang.ExceptionInInitializerError
E/AndroidRuntime( 3921): 	at com.pos.sdk.security.PosSecurityManager.getDefault(PosSecurityManager.java:217)
E/AndroidRuntime( 3921): 	at br.com.positivo.lib.bc.PinpadManager.<init>(PinpadManager.java:92)
E/AndroidRuntime( 3921): 	at br.com.positivo.lib.PinpadImpl.<init>(PinpadImpl.java:62)
E/AndroidRuntime( 3921): 	at br.com.positivo.lib.provider.PositivoDeviceProvider.getPinpad(PositivoDeviceProvider.java:50)
E/AndroidRuntime( 3921): 	at br.com.stone.posandroid.hal.positivo.api.bc.PinpadImpl.<init>(PinpadImpl.java:102)
E/AndroidRuntime( 3921): 	at br.com.stone.posandroid.hal.positivo.provider.PositivoDeviceProvider.getPinpad(PositivoDeviceProvider.java:80)
E/AndroidRuntime( 3921): 	at br.com.stone.posandroid.hal.compiler.log.generated.DeviceProviderLogger.getPinpad(DeviceProviderLogger.kt:21)
E/AndroidRuntime( 3921): 	at br.com.stone.posandroid.hal.compiler.log.generated.DeviceProviderLogger.getPinpad(DeviceProviderLogger.kt:10)
E/AndroidRuntime( 3921): 	at br.com.stone.posandroid.pal.hal.adapter.DeviceProviderAdapter.getPaymentApi(DeviceProviderAdapter.kt:68)
E/AndroidRuntime( 3921): 	at br.com.stone.pay.core.PAL.initializeDependencies(PAL.java:118)
E/AndroidRuntime( 3921): 	at br.com.stone.pay.core.PAL.initialize(PAL.java:91)
E/AndroidRuntime( 3921): 	at br.com.stone.pay.core.PAL.initialize(PAL.java:59)
E/AndroidRuntime( 3921): 	at stone.utils.PalHandler.initPal(PalHandler.kt:34)
E/AndroidRuntime( 3921): 	at stone.application.bootloader.steps.StepPALInit$execute$1.invoke(StepPALInit.kt:16)
E/AndroidRuntime( 3921): 	at stone.application.bootloader.steps.StepPALInit$execute$1.invoke(StepPALInit.kt:14)
E/AndroidRuntime( 3921): 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
E/AndroidRuntime( 3921): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.pos.sdk.security.IPosSecurity.registerListener(com.pos.sdk.security.IPosSecurityListener)' on a null object reference
E/AndroidRuntime( 3921): 	at com.pos.sdk.security.PosSecurityManager.<init>(PosSecurityManager.java:208)
E/AndroidRuntime( 3921): 	at com.pos.sdk.security.PosSecurityManager.<clinit>(PosSecurityManager.java:181)
E/AndroidRuntime( 3921): 	... 16 more
I/GED     ( 3921): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
I/GED     ( 3921): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
D/ViewRootImpl( 3921): setSurfaceViewCreated, created:false
V/PhoneWindow( 3921): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@58e8a1f, this = DecorView@ec0716c[MainActivity]
D/ProfileInstaller( 3921): Installing profile for dev.ltag.stone_payments_example
Lost connection to device.

Exited.

```

**Comment by Leleocastro** [comment]
Você seguiu este passo da documentação da Stone para maquininhas L4 Positivo?
https://sdkandroid.stone.com.br/v4.9.2/reference/processo-de-build-com-dispositivos-positivo

Caso tenha seguido, favor fornecer mais contexto, compartilhando seu build.gradle e a chamada da ativação.

**Comment by unleed-l** [comment]
Sim, eu segui esse processo da doc, exceto pelo último passo "6. Alterar o Build Variants para Positivo", pois não tenho o costume de utilizar o android studio e não consegui realizar este passo, poderia me auxiliar?

**Comment by Leleocastro** [comment]
No `app/build.gradle` você irá substituir o buildTypes atual pelo:
```gradle
buildTypes {
        release {
            shrinkResources false
            minifyEnabled true
            initWith debug
            signingConfig signingConfigs.positivo
            matchingFallbacks = ['debug']
        }
        debug {
            shrinkResources false
            minifyEnabled false
            initWith debug
            signingConfig signingConfigs.positivo
            matchingFallbacks = ['debug']
        }
    }
```

Lembre-se, conforme a documentação da Stone informa:

> Esse processo só é necessário para compilar o app em Debug para instalação nos terminais de Debug, para compilação em Release não é necessário realizar o processo, pois a JKS usada deve ser própria.

Se problema resolvido, favor fechar issue.

**Comment by unleed-l** [comment]
Resolveu! Muito obrigado pela ajuda. Você poderia adicionar esse buildTypes no app/build.gradle do example?

**Comment by Leleocastro** [comment]
Infelizmente não, pois isso fará com que não funcione para as outras maquinas.
