### ISSUE TITLE
Unable to add window

### ISSUE THREAD

**Issue by muriloventuroso** [Leleocastro/stone_payments#6]
Estou tendo o seguinte erro inicializar o SDK:

```
E/flutter (14620): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(UNAVAILABLE, Cannot Activate, android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?, null)
E/flutter (14620): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter (14620): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (14620): <asynchronous suspension>
E/flutter (14620): #2      MethodChannelStonePayments.activateStone (package:stone_payments/stone_payments_method_channel.dart:62:20)
E/flutter (14620): <asynchronous suspension>
```

**Comment by Leleocastro** [comment]
Olá @muriloventuroso, desculpa responder só agora, mas poderia dar mais contexto?
Como está ativando? Adicionou o código de ativação no método main? Qual maquininha está utilizando?
Se puder colar partes do seu código, por gentileza.

**Comment by unleed-l** [comment]
Estou passando pelo mesmo problema. Adicionei a variável "packageCloudReadToken" no local.porperties e também chamei a função de ativação no método main, porém este erro ocorre e a aplicação não é nem mesmo iniciada, fica em uma tela branca como se o app não executasse o runApp.
Estou utlizando o modelo L400.

Obs.: Tentei usando o example e ocorreu o mesmo erro.

```
V/StoneStart( 7786): init()
D/ViewRootImpl[Aguarde]( 7786): hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
E/flutter ( 7786): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(UNAVAILABLE, Cannot Activate, android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?, null)
E/flutter ( 7786): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter ( 7786): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 7786): <asynchronous suspension>
E/flutter ( 7786): #2      MethodChannelStonePayments.activateStone (package:stone_payments/stone_payments_method_channel.dart:62:20)
E/flutter ( 7786): <asynchronous suspension>
E/flutter ( 7786): #3      _stoneSetup (package:comandas/main.dart:38:3)
E/flutter ( 7786): <asynchronous suspension>
E/flutter ( 7786): #4      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
E/flutter ( 7786): <asynchronous suspension>
E/flutter ( 7786): #5      main (package:comandas/main.dart:58:3)
E/flutter ( 7786): <asynchronous suspension>
E/flutter ( 7786): 
I/stemas.comanda( 7786): Waiting for a blocking GC ProfileSaver
I/stemas.comanda( 7786): WaitForGcToComplete blocked ProfileSaver on ClassLinker for 51.211ms
I/stemas.comanda( 7786): WaitForGcToComplete blocked RunEmptyCheckpoint on ProfileSaver for 11.506ms
```

**Comment by unleed-l** [comment]
Aparentemente o que faz ocorrer este erro é a linha 24 do ActivateUsecase.kt:

`activeApplicationProvider.useDefaultUI(true)`

Porém, ao remover essa linha me retornou um novo erro que não consegui identificar por estar muito genérico:

```
V/StoneStart( 4700): init()
I/TetheringManager( 4700): registerTetheringEventCallback:dev.ltag.stone_payments_example
I/ping    ( 4700): PING google.com (142.251.129.238) 56(84) bytes of data.
I/ping    ( 4700): 64 bytes from gru14s34-in-f14.1e100.net (142.251.129.238): icmp_seq=1 ttl=117 time=38.0 ms
I/ping    ( 4700): 
I/ping    ( 4700): --- google.com ping statistics ---
I/ping    ( 4700): 1 packets transmitted, 1 received, 0% packet loss, time 0ms
I/ping    ( 4700): rtt min/avg/max/mdev = 38.069/38.069/38.069/0.000 ms
I/System.out( 4700): [okhttp]:check permission begin!
W/System  ( 4700): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out( 4700): [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out( 4700): [socket]:check permission begin!
W/System  ( 4700): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out( 4700): [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out( 4700): [OkHttp] sendRequest>>
I/System.out( 4700): [OkHttp] sendRequest<<
I/System.out( 4700): [okhttp]:check permission begin!
I/System.out( 4700): [okhttp]:not MMS!
I/System.out( 4700): [okhttp]:not Email!
I/System.out( 4700): [socket]:check permission begin!
I/System.out( 4700): [OkHttp] sendRequest>>
I/System.out( 4700): [OkHttp] sendRequest<<
D/ERROR   ( 4700): ERRO
E/flutter ( 4700): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Error, Error(exception=java.lang.Exception: Erro ao Ativar), Error(exception=java.lang.Exception: Erro ao Ativar), null)
E/flutter ( 4700): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter ( 4700): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 4700): <asynchronous suspension>
E/flutter ( 4700): #2      MethodChannelStonePayments.activateStone (package:stone_payments/stone_payments_method_channel.dart:62:20)
E/flutter ( 4700): <asynchronous suspension>
E/flutter ( 4700): #3      main (package:stone_payments_example/main.dart:15:3)
E/flutter ( 4700): <asynchronous suspension>
E/flutter ( 4700): 
```

**Comment by unleed-l** [comment]
Consegui encontrar o problema. No meu caso o problema foi a versão do sdk da stone, o package utiliza o sdk 4.3.11, porém a smart pos que utilizo (L400) só começou a ter suporte na versão 4.8.0 do sdk. Ao alterar o sdk para a versão 4.8.7 (mais recente), no build.gradle, a ativação ocorreu normalmente.

Também foi necessário remover a linha abaixo:

`activeApplicationProvider.useDefaultUI(true)`

Porém, mesmo conseguindo ativar, não estou conseguindo efetuar pagamentos (ocorre um erro) e nem imprimir (retorna sucesso, mas não imprime de fato).

Erro do pagamento:

```
E/ActivityThread( 5789): Failed to find provider info for br.com.stone.posandroid.settingsapp.service.terminal.settings
E/ayments_exampl( 5789): Invalid ID 0x00000000.
E/ActivityThread( 5789): Failed to find provider info for br.com.stone.posandroid.settingsapp.service.terminal.settings
I/chatty  ( 5789): uid=10099(dev.ltag.stone_payments_example) identical 2 lines
E/ayments_exampl( 5789): Invalid ID 0x00000000.
D/RESULT  ( 5789): ERROR
I/flutter ( 5789): PlatformException(Error, Error(exception=java.lang.Exception: ERROR), Error(exception=java.lang.Exception: ERROR), null)
```

**Comment by Leleocastro** [comment]
Fixed in new release #9
